### ISSUE TITLE
April 6th Livestream (Leveraging Feature Flags in Chatbot Conversations with LaunchDarkly and Postman)

### ISSUE THREAD

**Issue by Kcorb95** [Kcorb95/postman-devrel-marketing-tracker#14]
## Details:
**Title:** Leveraging Feature Flags in Chatbot Conversations with LaunchDarkly and Postman
**Date:** April 6th
**AirTable:** [Link to stream's AirTable entry](https://airtable.com/appJH2jdlldp5fm6Y/tblArXFnacRPiLVa2/viwbmF1GcMjUrnO7E/recv4gDvlzlCPogKT?blocks=hide)

## Tasks:
- [x] Thumbnail
- [x] Base Copy & YT Description
- [x] ReStream
- [x] Calendar Invites
- [x] Contentful / Events Page
- [x] Forum Post
- [x] 3x Social Posts

## Notes:
Should mention all hosts on Twitter so long as they have accounts. Aim for a 7 PM (or other IST favorable time) on Wednesday and the 5 minutes after starting on Thursday.

**Comment by sjwhitman** [comment]
Will add the forum post draft to notion today.

**Comment by sjwhitman** [comment]
ready to post here: https://www.notion.so/abecad4198634a509d6ae135713a6528?v=23c3c3e45fb346c3bce4fbfac1c55a24&p=9b5087714c574a0497862fc82b867778&pm=c
