### ISSUE TITLE
March 30th Livestream (Exploring Zoom REST & GraphQL APIs With Postman)

### ISSUE THREAD

**Issue by Kcorb95** [Kcorb95/postman-devrel-marketing-tracker#3]
## Details:
**Title:** Exploring Zoom REST & GraphQL APIs With Postman
**AirTable:** https://airtable.com/appJH2jdlldp5fm6Y/tblArXFnacRPiLVa2/viwdo6UY60EZUCHDd/recRyOeR39kCGIR4D?blocks=hide

## Tasks:
- [x] Thumbnail
- [x] Base Copy & YT Description
- [x] Restream
- [x] Calendar Invites
- [x] Contentful / Events Page
- [x] Forum Post
- [x] 3x Social Posts

## Notes:
Should mention all hosts on Twitter so long as they have accounts. Aim for a 7 PM (or other IST favorable time) on Wednesday and the 5 minutes after starting on Thursday.

**Comment by sjwhitman** [comment]
Copy is here, pretty confused about the stated times between Airbase and this GH ticket. Also need the meeting link. Copy is here: https://docs.google.com/document/d/1A8oABPx_ETNqXdsIuDWo1I7thz1o52In2QnaIhYKrLQ/edit?usp=sharing

Also I totally know Ojus! I reached out to him on Li about anything he might want us to call out.

**Comment by Kcorb95** [comment]
Thanks @sjwhitman !

I moved these over to the Notion so that it'll be a bit easier to collaborate and leave feedback.

Also some feedback:

- Start times for streams are always at 8 AM Pacific / 11 AM Eastern.
- The date mentioned in these tickets are meant to be a deadline for when we'd need deliverables completed by. Their individual scheduling depends on the AirTable date but we'd need to have all content finalized by whatever GH "due date". Let me know if this helps!
- Hosts and guests are already sent the restream invite link via a calendar invite that I send out.

- Updated the dates to occur next week. Forum post and first social post are typically on Monday the week of the stream.
- Also making sure that we mention Ojus _and_ Gianni as Zoom Developer Advocates.
- Otherwise this is a great first draft! I left some comments in Notion.

**Comment by sjwhitman** [comment]
Hey I really appreciate that detailed feedback. I'll start working on these edits now.
