### ISSUE TITLE
Codemotion Madrid Marketing

### ISSUE THREAD

**Issue by Kcorb95** [Kcorb95/postman-devrel-marketing-tracker#7]
## Details:
**Title:** Codemotion Madrid
**Date:** May 9-10th
**Location:** Madrid, Spain
**AirTable:** https://airtable.com/app3y5DRzWX0e7HsR/tbl0nPRnQndtNU50F/viwTVgxHYkF7GdvPT/recyHPV28T4WlgHaG?blocks=hide

## Tasks:
- [x] Contentful / Event Page
- [x] Forum Post
- [x] Socials

## Notes:
Socials should be once per week. ~2 weeks out from event, bump to 2x / week.
Be sure to spread out days and time zones. Mix of mentioning speakers and not mentioning speakers.
Value gained over WHO and the event itself.

Joyce confirmed speaking, Ian still pending (?)

**Comment by sjwhitman** [comment]
All socials are in and are ready for review.
